global abstract with sharing class OtterXOMConstants {

    //Order.vlocity_cmt__FulfilmentStatus__c
    public static final String CONST_ORDER_FULFILLMENT_STATUS_DRAFT         = 'Draft';
    public static final String CONST_ORDER_FULFILLMENT_STATUS_IN_PROGRESS   = 'In Progress';
    public static final String CONST_ORDER_FULFILLMENT_STATUS_ACTIVATED     = 'Activated';
    public static final String CONST_ORDER_FULFILLMENT_STATUS_SUPERSEDED    = 'Superseded';
    public static final String CONST_ORDER_FULFILLMENT_STATUS_CANCELED      = 'Canceled';

    //Order Item.Action
    public static final String CONST_ORDER_LINE_ITEM_ACTION_EXISTING        = 'Existing';
    public static final String CONST_ORDER_LINE_ITEM_ACTION_ADD             = 'Add';
    public static final String CONST_ORDER_LINE_ITEM_ACTION_CHANGE          = 'Change';
    public static final String CONST_ORDER_LINE_ITEM_ACTION_DISCONNECT      = 'Disconnect';
    public static final String CONST_ORDER_LINE_ITEM_ACTION_SUSPEND         = 'Suspend';
    public static final String CONST_ORDER_LINE_ITEM_ACTION_RESUME          = 'Resume';

    //Order Item.vlocity_cmt__ProvisioningStatus__c
    public static final String CONST_ORDER_LINE_ITEM_PROVISIONING_STATUS_NO_CHANGE  = 'NoChange';
    public static final String CONST_ORDER_LINE_ITEM_PROVISIONING_STATUS_NEW        = 'New';
    public static final String CONST_ORDER_LINE_ITEM_PROVISIONING_STATUS_CHANGED    = 'Changed';
    public static final String CONST_ORDER_LINE_ITEM_PROVISIONING_STATUS_DELETED    = 'Deleted';
    public static final String CONST_ORDER_LINE_ITEM_PROVISIONING_STATUS_SUSPENDED  = 'Suspended';
    public static final String CONST_ORDER_LINE_ITEM_PROVISIONING_STATUS_RESUMED    = 'Resumed';

}