global abstract with sharing class OtterTemplateUtils {
    
    /***************************************************************************************************************
    * @description brief description of method purpose
    * @param description of input parameters
    * @return description of output paramters
    * @example
    *
    * code snippet illustrating how to invoke the method
    */


    public void methodTemplate() {
        return;
    }
}
